baseURL = "http://example.org/"
languageCode = "nl"
title = "Labo Geavanceerd Chipdesign"

publishDir = "docs"

#baseurl = "https://brainbaking.com/"

theme = "hugo-theme-learn"

# enableEmoji = true
# enableRobotsTXT = true
# pygmentsCodefences = true

# for .Lastmod to work with .GitInfo: --enableGitInfo https://gohugo.io/variables/git/
enableGitInfo = true

[taxonomies]
    tag = "tags"

[params]
    disableComments = true
    themeVariant = "kul"
    disableInlineCopyToClipBoard = true

# see https://learn.netlify.com/en/basics/configuration/
[outputs]
home = [ "HTML", "RSS", "JSON"]

[Author]
  name = "Jo Vliegen"
  email = "<i>fname</i>.<i>lname</i>A T<i>esat.kuleuven.be</i>"

[[menu.shortcuts]] 
name = "<i class='fa fa-university'></i> Toledo"
identifier = "tol"
url = "TODO"
weight = 10

[[menu.shortcuts]] 
name = "<i class='fa fa-university'></i> ECTS Sheet"
identifier = "stud"
url = "https://uhintra03.uhasselt.be/studiegidswww/opleidingsonderdeel.aspx?a=2019&i=3467&n=4&t=01"
weight = 1